"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.setDefaultDuration = exports.getDefaultDuration = exports.waitUntilAsync = exports.waitUntil = exports.wait = exports.TimeoutError = exports.isTimeoutError = void 0;
var wait_1 = require("./wait");
Object.defineProperty(exports, "isTimeoutError", { enumerable: true, get: function () { return wait_1.isTimeoutError; } });
Object.defineProperty(exports, "TimeoutError", { enumerable: true, get: function () { return wait_1.TimeoutError; } });
Object.defineProperty(exports, "wait", { enumerable: true, get: function () { return wait_1.wait; } });
Object.defineProperty(exports, "waitUntil", { enumerable: true, get: function () { return wait_1.waitUntil; } });
Object.defineProperty(exports, "waitUntilAsync", { enumerable: true, get: function () { return wait_1.waitUntilAsync; } });
var options_1 = require("./options");
Object.defineProperty(exports, "getDefaultDuration", { enumerable: true, get: function () { return options_1.getDefaultDuration; } });
Object.defineProperty(exports, "setDefaultDuration", { enumerable: true, get: function () { return options_1.setDefaultDuration; } });
