# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master, abortOnError]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x, 18.x, 19.x, 20.x, 21.x, 22.x, 23.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
